const ACTIONS = {
    LOGIN: 'LOGIN',
    LOGINSTD: 'LOGINSTD',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_USER_SUP: 'GET_USER_SUP',
    GET_TOKENSTD:'GET_TOKENSTD'
}

export default ACTIONS